name: AppleMacMan
favicon: null
typography_spectrum: 0.79334
title: Apple Mac Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced5db'
    - '#3785ab'
    - '#050706'
    - '#f27a24'
    - '#284051'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
