name: null
favicon: null
layout_spectrum: 0.7741387283895165
typography_spectrum: 0.6619774145074189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4431452329736203
  lightness: 0.4216471058316529
  saturation: 0.6372289166320115
  rhythmicContrast: 0.6743254009634256
purpose: []
